include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - hash_and_equals
    - prefer_is_not_empty
    - avoid_as
    - avoid_print
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_logic_in_create_state
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - use_key_in_widget_constructors
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - directives_ordering
    - empty_catches
    - file_names
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - lines_longer_than_80_chars
    - no_runtimeType_toString
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - type_annotate_public_apis
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - use_function_type_syntax_for_parameters
    - use_string_buffers
    - use_to_and_as_if_applicable

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

  errors:
    avoid_as: error
    annotate_overrides: warning
    hash_and_equals: warning
    prefer_is_not_empty: warning
    avoid_print: warning
    avoid_returning_null_for_future: error
    avoid_slow_async_io: info
    cancel_subscriptions: error
    close_sinks: error
    control_flow_in_finally: error
    empty_statements: warning
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: warning
    no_logic_in_create_state: error
    prefer_void_to_null: info
    test_types_in_equals: warning
    throw_in_finally: error
    unnecessary_statements: warning
    use_key_in_widget_constructors: info
    always_put_control_body_on_new_line: info
    always_put_required_named_parameters_first: info
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_catches_without_on_clauses: info
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: warning
    avoid_equals_and_hash_code_on_mutable_classes: info
    avoid_field_initializers_in_const_classes: warning
    avoid_function_literals_in_foreach_calls: info
    avoid_implementing_value_types: warning
    avoid_positional_boolean_parameters: warning
    avoid_private_typedef_functions: warning
    avoid_redundant_argument_values: warning
    avoid_renaming_method_parameters: warning
    avoid_returning_null: warning
    avoid_setters_without_getters: info
    avoid_types_on_closure_parameters: info
    avoid_unnecessary_containers: warning
    avoid_void_async: info
    await_only_futures: warning
    camel_case_types: info
    cascade_invocations: info
    constant_identifier_names: info
    directives_ordering: warning
    empty_catches: warning
    file_names: warning
    flutter_style_todos: info
    join_return_with_assignment: info
    leading_newlines_in_multiline_strings: info
    lines_longer_than_80_chars: info
    no_runtimeType_toString: warning
    one_member_abstracts: ignore
    only_throw_errors: error
    overridden_fields: warning
    parameter_assignments: warning
    prefer_asserts_in_initializer_lists: info
    prefer_asserts_with_message: info
    prefer_const_constructors: info
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: info
    prefer_constructors_over_static_methods: info
    prefer_expression_function_bodies: warning
    prefer_final_locals: warning
    prefer_foreach: info
    prefer_function_declarations_over_variables: warning
    prefer_if_elements_to_conditional_expressions: info
    prefer_initializing_formals: info
    prefer_inlined_adds: info
    prefer_int_literals: info
    prefer_interpolation_to_compose_strings: info
    prefer_null_aware_operators: warning
    prefer_typing_uninitialized_variables: warning
    provide_deprecation_message: info
    type_annotate_public_apis: warning
    unnecessary_getters_setters: info
    unnecessary_lambdas: warning
    use_function_type_syntax_for_parameters: warning
    use_string_buffers: warning
    use_to_and_as_if_applicable: info
